### ISSUE TITLE
Crushdump mode and FPS counter 

### ISSUE THREAD

**Issue by F7usa** [mcdachpappe/android_kernel_oneplus_sdm845#8]
Great! There are only two issues: in oos 11.1.2.2 game space's FPS counter doesn't work and in Android 12.1 the phone goes After a few hours in crushdump mode.

**Comment by mcdachpappe** [comment]
Please get a log and share it with me, otherwise i won't be able to fix your crashdump issue since everything works as intended for me.

How to get a log? After ending up in crashdump mode: 
1. Reboot into recovery mode (don't do a system boot up, log file gets deleted if doing so)
2. Pull the logs at sys/fs/pstore or copy them into any internal storage dir
3. Zip the files and share them

**Comment by mcdachpappe** [comment]
- Broken FPS counter because of incomplete kernel sources

**Comment by mcdachpappe** [comment]
.

**Comment by mcdachpappe** [comment]
- Broken FPS counter because of incomplete kernel sources
